# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: nuage_de_son_development
  host: localhost
  username: stefanodevuono
  pool: 5
  timeout: 5000
